### ISSUE TITLE
yarn build

### ISSUE THREAD

**Issue by NotFounds** [enpitut2018/VideoSocialBookmarkFrontend#65]
yarn buildすると，/build以下に複数のファイルが生成されますが，javascriptを1ファイルにまとめることってできます？

**Comment by NotFounds** [comment]
https://github.com/enpitut2018/VideoSocialBookmark/pull/12
コンパイル結果を，/app/assets/javascriptとかに置きたい

**Comment by tomoyaf** [comment]
/build以下を/publicにおいてcontroller側で
```
render file: 'public/index.html', layout: false, content_type: 'text/html'
```
とかでできないかな

**Comment by tomoyaf** [comment]
というか、デフォルトで / はpublic/index.htmlを見るようになってるからfrontendをビルドするときに
```
yarn build; cp -r build/* ../VideoSocialBookmark/VideoSocialBookmark/public
```
みたいな感じにしたらできそう
