### ISSUE TITLE
ブックマークを隠してドロップダウンメニューにする

### ISSUE THREAD

**Issue by tomoyaf** [enpitut2018/VideoSocialBookmarkFrontend#90]
Bookmark Video のフォームを
DropdownMenuから選択して専用のページに移行する形
OR
DropdownMenuでその場にフォームが展開される形
にして、TOPページにはTrendとRecommendedだけにする

**Comment by tomoyaf** [comment]
理由としては
- そもそもこのサイトに来てからBookmarkするよりはGoogle ChromeのExtensionでやるほうが多そう

**Comment by kinironote** [comment]
#115
