### ISSUE TITLE
Frontendから実行できない

### ISSUE THREAD

**Issue by kinironote** [enpitut2018/VideoSocialBookmarkFrontend#91]
local storageがundefinedになる

**Comment by kinironote** [comment]
VideoSocialBookmarkFrontendリポジトリでは動かない
VideoSocialBookmarkリポジトリでは動くがいちいちbuildしないといけない
→hotreloadが欲しい

**Comment by NotFounds** [comment]
https://qiita.com/yakimeron/items/7a4f8d9e70a4a2b1b96b

**Comment by kinironote** [comment]
https://github.com/enpitut2018/VideoSocialBookmark/pull/112
