### ISSUE TITLE
MyPage(個人情報の表示)

### ISSUE THREAD

**Issue by kinironote** [enpitut2018/VideoSocialBookmarkFrontend#94]
getUser()が呼ばれてなくてstoreにuserが入ってない

**Comment by kinironote** [comment]
api/v1/userを見に行こうとしているがない

**Comment by NotFounds** [comment]
> /mypageで自分の情報も見たいと思うので/api/v1/meなどのアクセスポイントを作ってidを含むユーザーの個人情報を返すのが良さそう？

そのほうが良さそうですね👍
